require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RuleDiscountIfOneByMoresController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # RuleDiscountIfOneByMore. As you add validations to RuleDiscountIfOneByMore, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RuleDiscountIfOneByMoresController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all rule_discount_if_one_by_mores as @rule_discount_if_one_by_mores" do
      rule_discount_if_one_by_more = RuleDiscountIfOneByMore.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:rule_discount_if_one_by_mores)).to eq([rule_discount_if_one_by_more])
    end
  end

  describe "GET #show" do
    it "assigns the requested rule_discount_if_one_by_more as @rule_discount_if_one_by_more" do
      rule_discount_if_one_by_more = RuleDiscountIfOneByMore.create! valid_attributes
      get :show, {:id => rule_discount_if_one_by_more.to_param}, valid_session
      expect(assigns(:rule_discount_if_one_by_more)).to eq(rule_discount_if_one_by_more)
    end
  end

  describe "GET #new" do
    it "assigns a new rule_discount_if_one_by_more as @rule_discount_if_one_by_more" do
      get :new, {}, valid_session
      expect(assigns(:rule_discount_if_one_by_more)).to be_a_new(RuleDiscountIfOneByMore)
    end
  end

  describe "GET #edit" do
    it "assigns the requested rule_discount_if_one_by_more as @rule_discount_if_one_by_more" do
      rule_discount_if_one_by_more = RuleDiscountIfOneByMore.create! valid_attributes
      get :edit, {:id => rule_discount_if_one_by_more.to_param}, valid_session
      expect(assigns(:rule_discount_if_one_by_more)).to eq(rule_discount_if_one_by_more)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new RuleDiscountIfOneByMore" do
        expect {
          post :create, {:rule_discount_if_one_by_more => valid_attributes}, valid_session
        }.to change(RuleDiscountIfOneByMore, :count).by(1)
      end

      it "assigns a newly created rule_discount_if_one_by_more as @rule_discount_if_one_by_more" do
        post :create, {:rule_discount_if_one_by_more => valid_attributes}, valid_session
        expect(assigns(:rule_discount_if_one_by_more)).to be_a(RuleDiscountIfOneByMore)
        expect(assigns(:rule_discount_if_one_by_more)).to be_persisted
      end

      it "redirects to the created rule_discount_if_one_by_more" do
        post :create, {:rule_discount_if_one_by_more => valid_attributes}, valid_session
        expect(response).to redirect_to(RuleDiscountIfOneByMore.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved rule_discount_if_one_by_more as @rule_discount_if_one_by_more" do
        post :create, {:rule_discount_if_one_by_more => invalid_attributes}, valid_session
        expect(assigns(:rule_discount_if_one_by_more)).to be_a_new(RuleDiscountIfOneByMore)
      end

      it "re-renders the 'new' template" do
        post :create, {:rule_discount_if_one_by_more => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested rule_discount_if_one_by_more" do
        rule_discount_if_one_by_more = RuleDiscountIfOneByMore.create! valid_attributes
        put :update, {:id => rule_discount_if_one_by_more.to_param, :rule_discount_if_one_by_more => new_attributes}, valid_session
        rule_discount_if_one_by_more.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested rule_discount_if_one_by_more as @rule_discount_if_one_by_more" do
        rule_discount_if_one_by_more = RuleDiscountIfOneByMore.create! valid_attributes
        put :update, {:id => rule_discount_if_one_by_more.to_param, :rule_discount_if_one_by_more => valid_attributes}, valid_session
        expect(assigns(:rule_discount_if_one_by_more)).to eq(rule_discount_if_one_by_more)
      end

      it "redirects to the rule_discount_if_one_by_more" do
        rule_discount_if_one_by_more = RuleDiscountIfOneByMore.create! valid_attributes
        put :update, {:id => rule_discount_if_one_by_more.to_param, :rule_discount_if_one_by_more => valid_attributes}, valid_session
        expect(response).to redirect_to(rule_discount_if_one_by_more)
      end
    end

    context "with invalid params" do
      it "assigns the rule_discount_if_one_by_more as @rule_discount_if_one_by_more" do
        rule_discount_if_one_by_more = RuleDiscountIfOneByMore.create! valid_attributes
        put :update, {:id => rule_discount_if_one_by_more.to_param, :rule_discount_if_one_by_more => invalid_attributes}, valid_session
        expect(assigns(:rule_discount_if_one_by_more)).to eq(rule_discount_if_one_by_more)
      end

      it "re-renders the 'edit' template" do
        rule_discount_if_one_by_more = RuleDiscountIfOneByMore.create! valid_attributes
        put :update, {:id => rule_discount_if_one_by_more.to_param, :rule_discount_if_one_by_more => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested rule_discount_if_one_by_more" do
      rule_discount_if_one_by_more = RuleDiscountIfOneByMore.create! valid_attributes
      expect {
        delete :destroy, {:id => rule_discount_if_one_by_more.to_param}, valid_session
      }.to change(RuleDiscountIfOneByMore, :count).by(-1)
    end

    it "redirects to the rule_discount_if_one_by_mores list" do
      rule_discount_if_one_by_more = RuleDiscountIfOneByMore.create! valid_attributes
      delete :destroy, {:id => rule_discount_if_one_by_more.to_param}, valid_session
      expect(response).to redirect_to(rule_discount_if_one_by_mores_url)
    end
  end

end
